version: '3'
services:

  consul:
    image: consul:1.15
    command: agent -server -bootstrap-expect 1 -ui -data-dir /tmp -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - distribuidos

  app-config:
    build:
      context: ./app-config
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8888:8888"
    networks:
      - distribuidos
    depends_on:
      - consul

networks:
  distribuidos:
   external: true
  
