version: '3'
services:

  loadbalancer:
    build: 
      context: ./haproxy
      dockerfile: Dockerfile
    ports:
      - "9000:80"
      - "1936:1936"
    networks:
      - distribuidos

  express-gateway-data-store:
    image: redis:alpine
    container_name: express-gateway-data-store
    ports:
      - "6379:6379"
    networks:
      - distribuidos

  express-gateway:
    image: express-gateway
    container_name: express-gateway
    ports:
      - "8080:8080"
      - "9876:9876"
    networks:
      - distribuidos
    volumes:
      - type: bind
        source: ./appgw
        target: /var/lib/eg

networks:
  distribuidos:
    external: true
