version: '3'
services:

  postgres:
    build:
      context: ./resources/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      - distribuidos

  mysql:
    build:
      context: ./resources/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      - distribuidos

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - distribuidos


networks:
  distribuidos:
    external: true

